// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_c_rEU5amO4AWTM7_oOOCHqay2Xq6Pg',
    appId: '1:332757505850:web:1100abc22a76b289be2203',
    messagingSenderId: '332757505850',
    projectId: 'mindwell-app-18340',
    authDomain: 'mindwell-app-18340.firebaseapp.com',
    databaseURL: 'https://mindwell-app-18340-default-rtdb.firebaseio.com',
    storageBucket: 'mindwell-app-18340.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2ncyZpmo0uzbUFgCV6d3Xhimx0O3k8M',
    appId: '1:332757505850:android:aee7a988d80f50e9be2203',
    messagingSenderId: '332757505850',
    projectId: 'mindwell-app-18340',
    databaseURL: 'https://mindwell-app-18340-default-rtdb.firebaseio.com',
    storageBucket: 'mindwell-app-18340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8w4Up4QwqYA_FvfgarFEAhnGDaTf-9r0',
    appId: '1:332757505850:ios:d802534d0ccde06fbe2203',
    messagingSenderId: '332757505850',
    projectId: 'mindwell-app-18340',
    databaseURL: 'https://mindwell-app-18340-default-rtdb.firebaseio.com',
    storageBucket: 'mindwell-app-18340.firebasestorage.app',
    iosClientId: '332757505850-t5effle3l1kot9eukuniklarig8uq0th.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindwellFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8w4Up4QwqYA_FvfgarFEAhnGDaTf-9r0',
    appId: '1:332757505850:ios:d802534d0ccde06fbe2203',
    messagingSenderId: '332757505850',
    projectId: 'mindwell-app-18340',
    databaseURL: 'https://mindwell-app-18340-default-rtdb.firebaseio.com',
    storageBucket: 'mindwell-app-18340.firebasestorage.app',
    iosClientId: '332757505850-t5effle3l1kot9eukuniklarig8uq0th.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindwellFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt_c_rEU5amO4AWTM7_oOOCHqay2Xq6Pg',
    appId: '1:332757505850:web:b997e6396f591a0ebe2203',
    messagingSenderId: '332757505850',
    projectId: 'mindwell-app-18340',
    authDomain: 'mindwell-app-18340.firebaseapp.com',
    databaseURL: 'https://mindwell-app-18340-default-rtdb.firebaseio.com',
    storageBucket: 'mindwell-app-18340.firebasestorage.app',
  );
}
